import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Read one of the committed .cap fixtures in tests/ as raw bytes. */
export function fixtureBytes(name: string): Uint8Array {
  return new Uint8Array(
    readFileSync(fileURLToPath(new URL(`../${name}`, import.meta.url))),
  );
}

/** Read a fixture generated by tests/fixtures/global-setup.ts. */
export function generatedFixtureBytes(name: string): Uint8Array {
  return new Uint8Array(
    readFileSync(
      fileURLToPath(new URL(`../fixtures/generated/${name}`, import.meta.url)),
    ),
  );
}
