import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// NOTE: paths are joined at runtime (not via `new URL(name, import.meta.url)`)
// so Vite does not statically glob the fixture directories as assets.
const TESTS_DIR = fileURLToPath(new URL('..', import.meta.url));

function readBytes(...segments: string[]): Uint8Array {
  return new Uint8Array(readFileSync(join(TESTS_DIR, ...segments)));
}

/** Read one of the committed .cap fixtures in tests/ as raw bytes. */
export function fixtureBytes(name: string): Uint8Array {
  return readBytes(name);
}

/** Read a fixture generated by tests/fixtures/global-setup.ts. */
export function generatedFixtureBytes(name: string): Uint8Array {
  return readBytes('fixtures', 'generated', name);
}
